[module/xwindow]
type = internal/xwindow
format = <label>
format-prefix = 
format-prefix-font = ${module-prefix.font}
;format-prefix-padding = ${module-prefix.padding}
format-prefix-foreground = ${module-prefix.xwindow-fg}
format-background = ${block.bg}
format-foreground = ${block.fg}
;format-underline = ${ui.block-outline}
format-padding = ${block.pad}
format-margin = ${spacing.none}

label = %title:0:50:...%
label-padding = 1
label-empty = Desktop
label-empty-padding = 1

[module/filesystem]
type = internal/fs
interval = 25

;mount-0 = /

format-mounted = <label-mounted>
format-mounted-prefix = 
format-mounted-prefix-font = ${module-prefix.font}
;format-mounted-prefix-padding = ${module-prefix.padding}
format-mounted-prefix-foreground = ${module-prefix.filesystem-fg}
format-mounted-background = ${block.bg}
format-mounted-foreground = ${block.fg}
;format-mounted-underline = ${ui.block-outline}
format-mounted-padding = ${block.pad}
format-mounted-margin = ${spacing.none}

label-mounted = %free%
label-mounted-padding = 1
;label-unmounted = / n/a


[module/i3]
type = internal/i3

; Only show workspaces defined on the same output as the bar
;
; Useful if you want to show monitor specific workspaces
; on different bars
;
; Default: false
pin-workspaces = true

; Show urgent workspaces regardless of whether the workspace is actually hidden 
; by pin-workspaces.
;
; Default: false
; New in version 3.6.0
show-urgent = true

; This will split the workspace name on ':'
; Default: false
strip-wsnumbers = true

; Sort the workspaces by index instead of the default
; sorting that groups the workspaces by output
; Default: false
index-sort = true

; Create click handler used to focus workspace
; Default: true
enable-click = true

; Create scroll handlers used to cycle workspaces
; Default: true
enable-scroll = true

; Wrap around when reaching the first/last workspace
; Default: true
wrapping-scroll = true

; Set the scroll cycle direction 
; Default: true
reverse-scroll = false

; Use fuzzy (partial) matching for wc-icon.
; Example: code;♚ will apply the icon to all workspaces 
; containing 'code' in the name
; Changed in version 3.7.0: Selects longest string match instead of the first match.
; Default: false
fuzzy-match = true

; ws-icon-[0-9]+ = <label>;<icon>
; NOTE: The <label> needs to match the name of the i3 workspace
; Neither <label> nor <icon> can contain a semicolon (;)
ws-icon-0 = 1;♚
ws-icon-1 = 2;♛
ws-icon-2 = 3;♜
ws-icon-3 = 4;♝
ws-icon-4 = 5;♞
ws-icon-default = ♟
; NOTE: You cannot skip icons, e.g. to get a ws-icon-6
; you must also define a ws-icon-5.
; NOTE: Icon will be available as the %icon% token inside label-*

; Available tags:
;   <label-state> (default) - gets replaced with <label-(focused|unfocused|visible|urgent)>
;   <label-mode> (default)
format = <label-state> <label-mode>
format-background = ${i3block.bg}
format-foreground = ${i3block.fg}
format-padding = ${i3block.pad}
format-margin = ${spacing.none}

; Available tokens:
;   %mode%
; Default: %mode%
label-mode = %mode%
label-mode-padding = ${spacing.tight}
label-mode-background = ${i3block.bg}
label-mode-foreground = ${i3block.fg}
label-mode-underline = ${i3block.mode-underline}

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-focused = %index%
label-focused-foreground = ${i3block.bg}
label-focused-underline = ${i3block.focused-underline}
label-focused-padding = 1
label-focused-background = ${i3block.focused-underline}

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-unfocused = %index%
label-unfocused-foreground = ${i3block.fg}
label-unfocused-padding = ${spacing.none}

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-visible = %index%
label-visible-foreground = ${i3block.fg}
label-visible-underline = ${i3block.visible-underline}
label-visible-padding = ${spacing.none}

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-urgent = %index%
label-urgent-foreground = ${i3block.fg}
label-urgent-underline = ${i3block.urgent-underline}
label-urgent-padding = ${spacing.none}

; Separator in between workspaces
label-separator = |
label-separator-padding = ${spacing.tight}
label-separator-foreground = ${i3block.separator-fg}


[module/mpd]
type = internal/mpd
format-online = %{T3}<icon-prev> <icon-stop> <toggle> <icon-next> %{T1}<label-time> <bar-progress> %{T1}<label-song>
format-online-overline = ${module-mpd.format-line}
format-online-underline = ${module-mpd.format-line}
format-offline = <label-offline>
label-offline = mpd is off

icon-play = ⏵
icon-pause = ⏸
icon-stop = ⏹
icon-prev = ⏮
icon-next = ⏭
icon-seekb = 
icon-seekf = 
icon-random = 列
icon-repeat = 凌
icon-repeatone = 綾
icon-single = 綾
icon-consume = ✀

label-song-maxlen = 100
label-song-ellipsis = true

bar-progress-width = 20
bar-progress-format = %{+o +u}%fill%%{-o -u}%indicator%%{+o +u}%empty%%{-u -o}
; bar-progress-indicator = |
bar-progress-indicator = █
bar-progress-indicator-foreground = ${module-mpd.progress-indicator-fg}
bar-progress-indicator-font = 3
; bar-progress-fill = ─
bar-progress-fill = █
bar-progress-fill-foreground = ${module-mpd.progress-fill-fg}
bar-progress-fill-font = 3
; bar-progress-empty = ─
bar-progress-empty = ▒
bar-progress-empty-font = 3
bar-progress-empty-foreground = ${module-mpd.progress-empty-fg}

toggle-on-foreground = ${module-mpd.toggle-on-fg}
toggle-off-foreground = ${module-mpd.toggle-off-fg}




[module/cpu]
type = internal/cpu
interval = 0.2
format = <label>
format-prefix = 
format-prefix-font = ${module-prefix.font}
;format-prefix-padding = ${module-prefix.padding}
format-prefix-foreground = ${module-prefix.cpu-fg}
format-background = ${block.bg}
format-foreground = ${block.fg}
;format-underline = ${ui.block-outline}
format-padding = ${block.pad}
format-margin = ${spacing.none}

label = %percentage:2%%
label-padding = 1
;label-font = 5

ramp-coreload-spacing = 1
ramp-coreload-font = 3
ramp-coreload-0 = ▁
ramp-coreload-1 = ▂
ramp-coreload-2 = ▃
ramp-coreload-3 = ▄
ramp-coreload-4 = ▅
ramp-coreload-5 = ▆
ramp-coreload-6 = ▇
ramp-coreload-7 = █

[module/memory]
type = internal/memory
interval = 0.2
format = <label>

format-prefix = 
;format-prefix-padding = ${module-prefix.padding}
format-prefix-foreground = ${module-prefix.memory-fg}
format-prefix-font = ${module-prefix.font}
format-foreground = ${block.fg}
format-background = ${block.bg}
;format-underline = ${ui.block-outline}
format-padding = ${block.pad}
format-margin = ${spacing.none}


; label = %percentage_used:2%%

label = %percentage_used:2%%
label-padding = 1
;label-font = 1

bar-used-width = 10
bar-used-gradient = true
bar-used-foreground-0 = ${module-memory.bar-foreground-0}
bar-used-foreground-1 = ${module-memory.bar-foreground-1}
bar-used-foreground-2 = ${module-memory.bar-foreground-2}
bar-used-foreground-3 = ${module-memory.bar-foreground-3}
bar-used-indicator = █
bar-used-indicator-font = 3
bar-used-indicator-foreground = ${module-memory.bar-indicator-fg}
bar-used-fill = █
bar-used-fill-font = 3
bar-used-empty = █
bar-used-empty-font = 3
bar-used-empty-foreground = ${module-memory.bar-empty-fg}

[module/wlan]
type = internal/network
interface = ${env:WIRELESS_NAME}
interval = 3.0

format-connected = <ramp-signal><label-connected>
; format-connected-prefix = " "
; format-connected = <label-connected>
format-connected-underline = ${module-network.wlan-underline}

# The text
label-connected = %essid% ↑%upspeed% ↓%downspeed%
label-font = 1
label-connected-background = ${module-network.label-bg}
label-connected-padding = ${spacing.none}

ramp-signal-font = 2
ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-5 = 
ramp-signal-padding = ${spacing.tight}
ramp-signal-foreground = ${module-network.ramp-fg}
; ramp-signal-background = ${colors.background-alt}

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

[module/eth]
type = internal/network
interface = ${env:ETH_NAME}
interval = 3.0

format-connected-underline = ${module-network.eth-underline}
format-connected-prefix = ""
format-connected-prefix-foreground = ${module-network.prefix-fg}
label-connected = %local_ip% ↑%upspeed% ↓%downspeed%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

[module/date]
type = internal/date
interval = 1

date = %d %b
date-alt = "%A %d %B %Y"
time = %H:%M
time-alt = %T
format = <label>
format-prefix = 
format-prefix-font = ${module-prefix.font}
;format-prefix-padding = ${module-prefix.padding}
format-prefix-foreground = ${module-prefix.date-fg}
format-background = ${block.bg}
format-foreground = ${block.fg}
;format-underline = ${ui.block-outline}
format-padding = ${block.pad}
format-margin = ${spacing.none}

label = %time% · %date%
label-padding = 1

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%
label-volume-foreground = ${module-audio.label-fg}

format-volume-background = ${block.bg}
format-volume-foreground = ${block.fg}
;format-volume-underline = ${ui.block-outline}
format-volume-padding = ${block.pad}
format-volume-margin = ${spacing.none}

label-muted =  muted
label-muted-foreground = ${module-audio.muted-fg}

bar-volume-width = 10
bar-volume-foreground-0 = ${module-audio.bar-foreground-0}
bar-volume-foreground-1 = ${module-audio.bar-foreground-1}
bar-volume-foreground-2 = ${module-audio.bar-foreground-2}
bar-volume-foreground-3 = ${module-audio.bar-foreground-3}
bar-volume-foreground-4 = ${module-audio.bar-foreground-4}
bar-volume-foreground-5 = ${module-audio.bar-foreground-5}
bar-volume-foreground-6 = ${module-audio.bar-foreground-6}
bar-volume-foreground-7 = ${module-audio.bar-foreground-7}
bar-volume-foreground-8 = ${module-audio.bar-foreground-8}
bar-volume-foreground-9 = ${module-audio.bar-foreground-9}
bar-volume-gradient = false
bar-volume-indicator = █
bar-volume-indicator-font = 2
bar-volume-fill = █
bar-volume-fill-font = 2
bar-volume-empty = ▒
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${module-audio.bar-empty-fg}

ramp-volume-font = 6
ramp-volume-foreground = ${module-audio.ramp-fg}
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

[module/alsa]
type = internal/alsa

format-volume = <label-volume> <bar-volume>
label-volume = VOL
label-volume-foreground = ${module-audio.label-fg}

format-muted-prefix = " "
format-muted-foreground = ${module-audio.muted-fg}
label-muted = sound muted

bar-volume-width = 10
bar-volume-foreground-0 = ${module-audio.bar-foreground-0}
bar-volume-foreground-1 = ${module-audio.bar-foreground-1}
bar-volume-foreground-2 = ${module-audio.bar-foreground-2}
bar-volume-foreground-3 = ${module-audio.bar-foreground-3}
bar-volume-foreground-4 = ${module-audio.bar-foreground-4}
bar-volume-foreground-5 = ${module-audio.bar-foreground-5}
bar-volume-foreground-6 = ${module-audio.bar-foreground-6}
bar-volume-foreground-7 = ${module-audio.bar-foreground-7}
bar-volume-foreground-8 = ${module-audio.bar-foreground-8}
bar-volume-foreground-9 = ${module-audio.bar-foreground-9}
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${module-audio.bar-empty-fg}


[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <label>
format-prefix = 
format-prefix-font = ${module-prefix.font}
;format-prefix-padding = ${module-prefix.padding}
format-prefix-foreground = ${module-prefix.temperature-fg}
format-background = ${block.bg}
format-foreground = ${block.fg}
;format-underline = ${ui.block-outline}
format-padding = ${block.pad}
format-margin = ${spacing.none}
format-warn = <label-warn>
format-warn-underline = ${module-temp.warn-underline}

label = %temperature-c%
label-padding = 1
label-warn = %temperature-c%
label-warn-padding = 1
label-warn-foreground = ${module-temp.warn-fg}

[module/tray-toggle]
type = custom/script
exec = ~/.config/polybar/scripts/tray_toggle.sh
tail = true

;format-background = ${block.bg}
;format-foreground = ${block.fg}
format-padding = ${block.pad}
;format-margin = ${block.gap}
;format-font = 6

click-left = kill -USR1 %pid%
env-START_TRAY_HIDDEN = true

[module/updates-pacman-aurhelper]
type = custom/script
exec = ~/.config/polybar/scripts/updates-pacman-aurhelper.sh
interval = 600

format-prefix = 󰏗
format-prefix-font = ${module-prefix.font}
format-prefix-foreground = ${module-prefix.updates-fg} 

format = <label>
label = %output%
label-padding = 1
format-background = ${block.bg}
format-foreground = ${block.fg}
;format-underline = ${ui.block-outline}
format-padding = ${block.pad}
format-margin = ${spacing.none}

[module/openweathermap-fullfeatured]
type = custom/script
exec = ~/.config/polybar/scripts/openweathermap-fullfeatured.sh
interval = 600
label-font = 4

; vim:ft=dosini
